spring:
  datasource:
    url: jdbc:mysql://139.196.6.63:3306/fmp?serverTimezone=UTC
    username: root
    password: mengkefmp
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jps:
    showsql: true
server:
  port: 9080
mybatis:
  mapper-locations: classpath:mapper/*.xml
